version: "3.5"
services:
  postgresql:
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13
  temporal:
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - PROMETHEUS_ENDPOINT=0.0.0.0:9000
    image: temporalio/auto-setup:1.17.0
    ports:
      - 7233:7233
  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-remote-write-receiver
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus/config.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
