limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true # Dev setup only. Please don't turn this on in production.
    constraints: {}
matching.numTaskqueueReadPartitions:
  - value: 4
    constraints: {}
matching.numTaskqueueWritePartitions:
  - value: 4
    constraints: {}
